id: I39422A45
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T22:22:35.045184'
last_modified: '2022-06-18T22:22:35.045200'
parser: null
source_metadata:
  title: Tshal pa kun dga rdo rjes (1309–1364) s Sakya Genealogy
  author: tshal pa kun dga rdo rje/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2018-09-06); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Lobsang Gyaltsen, Dharamsala (lg)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/2437
  bases:
    663a:
      title: Tshal pa kun dga rdo rjes (1309–1364) s Sakya Genealogy
      order: 1
      base_file: 663a.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
